### ISSUE TITLE
Migrate all ExchangeRule.parseRuleBlock calls to playerInteractionEvent

### ISSUE THREAD

**Issue by erocs** [Civcraft/ItemExchange#17]
Perf bug. For a long time ItemExchangeListener.onInventoryMove has been a good hit to hopper performance, due to the inventory scan and metadata parsing. This bug is to determine the feasibility of removing all ExchangeRule.parseRuleBlock calls from their current locations and implement the change to make ItemExchangeListener.playerInteractionEvent be the only caller.

It's possible that a per-container flag should be used in place of parseRuleBlock at all the current call sites to notify playerInteractionEvent when parseRuleBlock needs to be called.

**Comment by Maxopoly** [comment]
I just took a look at the whole thing for a while and the only purpose of the onInventoryMove and onInventoryPickupItem listeners seems to be preventing hoppers from picking up rule blocks, right? Why not just change it so that at the start of both listeners, it checks whether the moved item is a stone button and if not, it returns right away?

**Comment by erocs** [comment]
If you choose to fix this go with whichever methodology works best to improve perf of this event handler. I was only quickly thinking about how to eliminate the parsing.

**Comment by Maxopoly** [comment]
Fixed here: https://github.com/Civcraft/ItemExchange/pull/18
